- name: Ansible template Demonstration
  hosts: myhosts
  vars: 
    app_name: "MyApp"
    env: "production"
    version: "1.0.0"
    db_host: "localhost"
    db_port: 3306
    db_name: "myapp_db"
    db_user: "admin"
    db_password: "pass123"

  tasks: 
  - name: Create destination directory for configuration file
    file:
      path: /home/ashutosh/IIITB/DevOps/Ansible/8th/configurations
      state: directory

  - name: Create a configuration file using template
    template:
      src: template/config.j2
      dest: /home/ashutosh/IIITB/DevOps/Ansible/8th/configurations/app_config.yml

  - name: Display the generated config file
    command: cat /home/ashutosh/IIITB/DevOps/Ansible/8th/configurations/app_config.yml
    register: output

  - name: Print the configuration details
    debug:
      msg: "{{ output.stdout }}"