# Configuration File Generated via Ansible Template
application_name: MyApp
environment: production
version: 1.0.0

# Database Configuration
db_host: localhost
db_port: 3306
db_name: myapp_db
db_user: admin
db_password: password123