- name: Example Playbook with Different Variable Data Types
  hosts: localhost
  vars:
    # String Variable
    string_var: "Hello, Ansible!"

    # Numerical Variable
    num_var: 56

    # List Variable
    list_var:
      - item1
      - 12
      - item2

    # dictonary variable
    dict_var:
      key1: value1
      key2: value2
      key3: value3

    # boolean variable
    bool_var: true
  
  tasks:
    - name: Display Variables
      debug:
        msg:
          - "String Variable: {{ string_var }}"
          - "NUmeric Variable: {{ num_var }}"
          - "list: {{ list_var }}"
          - "dictonary: {{ dict_var }}"
          - "boolean: {{ bool_var }}"